CREATE TABLE st_marksheet (
  ID bigint(20) NOT NULL,
  ROLL_NO varchar(255) DEFAULT NULL,
  STUDENT_ID bigint(20) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  PHYSICS int(11) DEFAULT NULL,
  CHEMISTRY int(11) DEFAULT NULL,
  MATHS int(11) DEFAULT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  MODIFIED_BY varchar(255) DEFAULT NULL,
  CREATED_DATETIME datetime DEFAULT NULL,
  MODIFIED_DATETIME datetime DEFAULT NULL,
  rollno varchar(20) DEFAULT NULL,
  studentid bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID)
) 
